server:
  port: 20000

spring:
  application:
    name: gulimall-auth-server
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  redis:
    host: localhost
    port: 6379
  thymeleaf:
    cache: false
  # spring-session 整合使用redis存储
  session:
    store-type: redis

oauth2:
  weibo:
    client-id: 123456
    client-secret: 123456
    grant-type: authorization_code
    redirect-uri: http://auth.gulimall.com/oauth2/weibo/success