server:
  port: 9000

spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    # seata 老版本 配置
#    alibaba:
#      seata:
#        tx-service-group: ${spring.application.name}-fescar-service-group
  application:
    name: gulimall-order
  redis:
    host: localhost
    port: 6379
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/gulimall_oms?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
  session:
    store-type: redis
  # rabbitmq配置
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /
    username: guest
    password: guest
    # ***************************************************************************************
    # 开启发送端消息确认机制（消息可靠性）
    # confirms：客户端消息是否发抵达了交换机确认。
    # publisher-returns：交换机消息是否抵达了队列确认。
    # template.mandatory：只要消息抵达了队列，就优先回调returns方法。
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
    # 开启接收端消息确认机制（消息可靠性）：一般都全部开启手动确认机制！
    # manual：手动确认
    listener:
      simple:
        acknowledge-mode: manual
    # ***************************************************************************************

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

# 本项目自定义线程池
gulimall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10
