server:
  port: 12000


spring:
  application:
    name: gulimall-search
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  # thymeleaf模板引擎
  thymeleaf:
    cache: false

elasticsearch:
  host: localhost
  port: 9200
  scheme: http