server:
  port: 12000


spring:
  application:
    name: gulimall-search
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

elasticsearch:
  host: localhost
  port: 9200
  scheme: http