server:
  # TODO 为方便本地调试 此处 88 端口 修改为 80 端口
  port: 80

spring:
  application:
    name: gulimall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        # networkInterface: localhost:88
#    loadbalancer:
#      ribbon:
#        enabled: false
    gateway:
      routes:
        # gulimall-product 项目的路由
        - id: product_route
          uri: lb://gulimall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
        # gulimall-member 项目的路由
        - id: member_route
          uri: lb://gulimall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
        # gulimall-ware 项目的路由
        - id: ware_route
          uri: lb://gulimall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
        # gulimall-coupon 项目的路由
        - id: coupon_route
          uri: lb://gulimall-coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
        # gulimall-order 项目的路由
        - id: order_route
          uri: lb://gulimall-order
          predicates:
            - Path=/api/order/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
        # gulimall-third-party 项目的路由
        - id: third_party_route
          uri: lb://gulimall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
        # renren-fast 项目的路由
        - id: admin_root
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          # 重写路径 满足 renren-fast 要求
          filters:
            # RewritePath 原地址, 重写后地址
            # /api/xxx -> /renren-fast/xxx
            - RewritePath=/api/(?<segment>.*), /renren-fast/$\{segment}

        # 前端前台静态页面路由
        - id: gulimall_host_route
          uri: lb://gulimall-product
          predicates:
            - Host=gulimall.com,item.gulimall.com

        - id: gulimall_search_route
          uri: lb://gulimall-search
          predicates:
            - Host=search.gulimall.com

        - id: gulimall_auth_route
          uri: lb://gulimall-auth-server
          predicates:
            - Host=auth.gulimall.com


