server:
  port: 30000

spring:
  application:
    name: gulimall-cart
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  thymeleaf:
    cache: false
  redis:
    host: localhost
    port: 6379


# 本项目自定义线程池
gulimall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10


